export const Languages = [
    "Arabic",
    "Arabic (Egyptian)",
    "Arabic (Levantine)",
    "Arabic (Maghrebi)",
    "Arabic (Modern Standard)",
    "Bengali",
    "Bengali (Standard)",
    "Bengali (Sylheti)",
    "Catalan",
    "Chinese",
    "Chinese (Mandarin)",
    "Chinese (Sichuanese)",
    "Chinese (Simplified)",
    "Chinese (Traditional)",
    "Czech",
    "Danish",
    "Dutch",
    "English",
    "English (American)",
    "English (British)",
    "Estonian",
    "Finnish",
    "French",
    "German",
    "Greek",
    "Gujarati",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Indonesian",
    "Italian",
    "Japanese",
    "Kannada",
    "Korean",
    "Malay",
    "Malayalam",
    "Marathi",
    "Norwegian",
    "Norwegian (Bokmål)",
    "Odia",
    "Polish",
    "Portuguese",
    "Portuguese (Brazilian)",
    "Portuguese (Portugal)",
    "Punjabi",
    "Romanian",
    "Russian",
    "Spanish",
    "Spanish (South America)",
    "Swedish",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Bulgarian",
    "Latvian",
    "Lithuanian",
    "Slovak",
    "Slovene",
    'Mayan',
    'Filipino',
    'Persian',
    'Croatian',
    'Serbian',
    'Icelandic',
    'Samoan',
    'Cantonese'
].sort();